### ISSUE TITLE
Too fast for S3 (SlowDown)

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/tool-aws#10]
Exception: An error occurred (SlowDown) when calling the DeleteObjects operation (reached max retries: 4): Please reduce your request rate.

Sometimes, we are too fast for S3, it's good news but the script shouldn't fail for this reason.

Action:
Catch SlowDown errors and use timeouts to make sure we still delete everything at the fastest possible rate.

This happened when deleting 2 backend caches on 2 xlarge clusters.

**Comment by ltclm** [comment]
yes!
