### ISSUE TITLE
Suspicious number of keys

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/tool-aws#5]
By massive layers delete, I always have 32'000 keys, which is a bit suspicous...

```
INFO:tool_aws.s3.rm:Deletion started...
INFO:tool_aws.s3.rm:Warning: the script will now delete:
INFO:tool_aws.s3.rm:\n
            Number of keys: 32000
            Chunk size    : 1000
            Prefix        : 1.0.0/ch.swisstopo.swisstlm3d-karte-farbe/default/20150401/3857/

```

**Comment by loicgasser** [comment]
It's 32 000 by 32 000 that they are deleted. You probably have more Keys. Did you actually launch the cmd ?

**Comment by loicgasser** [comment]
And it will delete them all 32000 by 32000 until you have no more Keys. Maybe there is a bug, but I doubt it.

**Comment by loicgasser** [comment]
And 1 batch request of 1000 Keys are sent. So basically if you have 2 cores, it will first list the first 32 000 Keys and send batch delete of a 1000 Keys over 2 threejs. Most likely each thread will delete 16 000 Keys. And then we list again and so on.

**Comment by loicgasser** [comment]
And 1 batch delete request of 1000 Keys are sent. So basically if you have 2 cores, it will first list the first 32 000 Keys and send batch delete of a 1000 Keys over 2 threejs. Most likely each thread will delete 16 000 Keys. And then we list again and so on.

**Comment by loicgasser** [comment]
And 1 batch delete request of 1000 Keys are sent. So basically if you have 2 cores, it will first list the first 32 000 Keys and send batch delete of a 1000 Keys over 2 threads. Most likely each thread will delete 16 000 Keys. And then we list again and so on.

**Comment by procrastinatio** [comment]
No `s3rm` efffectively erase all tiles, only the reporting is strange.

**Comment by loicgasser** [comment]
Ok I ll look into it
