### ISSUE TITLE
Infinite loop when deleting files from a bucket beeing used

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/tool-aws#7]
Case:
Someone is using mapproxy on a given layer. Tiles are constantly generated.

The **s3rm** script is deleting the files as soon as they are generated, never ending.

**Comment by procrastinatio** [comment]
Case:
Someone is using mapproxy on a given layer. Tiles are constantly generated.

The **s3rm** script is deleting the files as soon as they are generated, never ending-

**Comment by loicgasser** [comment]
s3rm doesn't  stop as long as tiles with a matching path are still found in the bucket.

**Comment by loicgasser** [comment]
I could avoid this behaviour I think. If we get two times in row less than the maximal number of entries, we can deduce that somebody is adding new entries at the same time.
I will propose a PR that nobody will ever review and that I will self merge.

**Comment by gjn** [comment]
Why, we have 6 people in our team- we have Andrea as well.

Please talk to each other regarding reviews.

**Comment by danduk82** [comment]
I don't think this risk exist, as the code gets the list of keys once, and then delete the keys that it has received once. There is no `while True ` on key listing...

**Comment by gjn** [comment]
I think we can close this, no?

**Comment by loicgasser** [comment]
Yep
